"""Per-document prompts + validators for the KIRO spec set (multi-doc spec R1).

Shared by generation (blocking validation + repair pass) and the editor
(advisory warnings on manual save).
"""

import re

DOC_TYPES = ("requirements", "design", "tasks")

AWS_SERVICE_ALLOWLIST = (
    "Lambda, API Gateway, S3, DynamoDB, RDS, OpenSearch, Bedrock, Step Functions, "
    "EventBridge, SQS, SNS, CloudWatch, KMS, Cognito"
)

REQUIREMENTS_SYSTEM = """You are marshal's specification writer. Transform the conversation into a complete, KIRO-compatible requirements document.

Output RAW MARKDOWN ONLY (no code fences around the whole document, no commentary) with exactly this skeleton:

# Requirements — <App Name>

## Introduction
<2-4 sentence overview of the application and the problem it solves>

## Functional Requirements
### FR-1: <name>
**User story:** As a <actor>, I want <capability>, so that <benefit>.
**Acceptance criteria:**
1. WHEN <condition> THEN the system SHALL <behavior>.
(repeat FR-2, FR-3, ... for every distinct capability discussed)

## Non-Functional Requirements
- <performance, security, availability, usability expectations>

## Constraints
- <technical or business constraints from the conversation>

## Assumptions
- <every assumption you made where the conversation was ambiguous — this section is mandatory and must never be empty; if everything was specified, state the baseline assumptions you inherited>

Rules: derive content strictly from the conversation; do not invent features that were never discussed; keep AWS service references within: {allowlist}."""

DESIGN_SYSTEM = """You are marshal's solution architect. Produce a KIRO-compatible design document for the application, based on the finalized requirements document and the conversation.

Output RAW MARKDOWN ONLY with exactly this skeleton:

# Design — <App Name>

## Architecture Overview
<2-4 sentences describing the overall approach>

```mermaid
graph TD
  <auto-generated architecture diagram of the main components and data flows>
```

## Component Breakdown
### <Component name>
<responsibility, key behaviors, interfaces>
(repeat per component)

## Data Model
<entities/tables/indexes with fields; use fenced blocks or bullet lists>

## API Contracts
<REST endpoints or event contracts if the app exposes any; write "Not applicable" only if truly none>

## Technology Choices
| Concern | Choice | Rationale |
(only AWS services from: {allowlist})

## Security Considerations
- <authn/authz, data protection, secrets, network posture, PII handling>

Rules: every functional requirement must be traceable to a component; the mermaid block is mandatory and must be valid mermaid `graph TD` syntax; do not invent requirements."""

TASKS_SYSTEM = """You are marshal's delivery planner. Decompose the requirements + design into an ordered, dependency-aware implementation plan in KIRO tasks format.

Output RAW MARKDOWN ONLY with exactly this skeleton:

# Implementation Plan — <App Name>

- [ ] 1. <First task — foundational> _(Req: FR-x[, FR-y])_
  - <1-3 bullet details of the work>
  - Test: <how this task is verified>
- [ ] 2. <Next task> _(Req: FR-x)_
  - ...
  - Test: ...
(continue for the full build; typically 6-14 tasks; later tasks may depend on earlier ones — order accordingly)

Rules: every FR from the requirements document must be covered by at least one task; each task lists a Test criterion; keep tasks buildable in sequence; no placeholder text."""

REPAIR_SYSTEM = """The following markdown document does not conform to the required skeleton for a {doc_type} document (missing required sections or malformed structure). Rewrite it so it conforms exactly, preserving all substantive content. Output raw markdown only."""

REQUIRED_SECTIONS: dict[str, list[str]] = {
    "requirements": [
        "# Requirements",
        "## Introduction",
        "## Functional Requirements",
        "## Assumptions",
    ],
    "design": [
        "# Design",
        "## Architecture Overview",
        "## Component Breakdown",
        "## Data Model",
        "## Technology Choices",
        "## Security Considerations",
    ],
    "tasks": ["# Implementation Plan"],
}

_CHECKBOX_RE = re.compile(r"^- \[[ x]\] \d+\.", re.MULTILINE)
_MERMAID_RE = re.compile(r"```mermaid\s")


def system_prompt_for(doc_type: str) -> str:
    prompts = {
        "requirements": REQUIREMENTS_SYSTEM,
        "design": DESIGN_SYSTEM,
        "tasks": TASKS_SYSTEM,
    }
    return prompts[doc_type].replace("{allowlist}", AWS_SERVICE_ALLOWLIST)


def strip_fences(content: str) -> str:
    text = content.strip()
    match = re.match(r"^```(?:markdown|md)?\s*\n(.*)\n```$", text, re.DOTALL)
    return match.group(1).strip() if match else text


def validate_doc(doc_type: str, content: str) -> list[str]:
    """Return a list of validation problems (empty = valid)."""
    problems: list[str] = []
    if not content or not content.strip():
        return ["Document is empty"]
    for section in REQUIRED_SECTIONS.get(doc_type, []):
        if section not in content:
            problems.append(f"Missing required section: {section}")
    if doc_type == "design" and not _MERMAID_RE.search(content):
        problems.append("Missing mermaid architecture diagram (```mermaid block)")
    if doc_type == "tasks" and not _CHECKBOX_RE.search(content):
        problems.append("No KIRO checkbox tasks found (- [ ] N. ...)")
    return problems


def is_valid(doc_type: str, content: str) -> bool:
    return not validate_doc(doc_type, content)
